### ISSUE TITLE
Possibly Re-Add Installation-Script to Download-Page?

### ISSUE THREAD

**Issue by kianagit** [Vencord/vencord.dev#31]
Maybe it's a cool idea to re-add the installation-script (windows) to the website, which is located at https://github.com/Vencord/Installer/blob/main/install.ps1

I remember it being there, but now it seemingly got removed.

edit: for instance, you could use a powershell command to install it without downloading anything manually: 
`iwr https://github.com/Vencord/Installer/blob/main/install.ps1 | iex`

**Comment by lewisakura** [comment]
the CLI command was changed because the script is just a wrapper around downloading the CLI installer, which we recommend getting directly instead.
