### ISSUE TITLE
No longer able to right-click and copy enlarged images to the clipboard.

### ISSUE THREAD

**Issue by JThundley** [Vencord/vencord.dev#36]
As of the last 2-3 git releases, I'm no longer able to copy enlarged images to the clipboard.

Steps to reproduce:

1. Click on an image in vencord so that you see the larger image that darkens the main interface.
2. Right click on this image, select "copy image".
3. Try to paste it somewhere. It won't work because it never makes it into the clipboard.

Expected outcome:
I expected the image to copy to my clipboard when clicking copy.

I noticed that doing a right click and copy on inline image in chat works fine. It's just when an image is enlarged. I also tried disabling the image zoom plugin which didn't help. I'm running the vencord-desktop-git arch package with the following versions:

- Stable 260101 (e220e75)
- Vencord 8a168bd (Vesktop V1.5.0)
- Electron 28.1.3
- Chromium 120.0.6099.199

**Comment by Vendicated** [comment]
very very wrong repo + duplicate
